apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  # labels:
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "*.eduardoschulz.com.br"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.eduardoschulz.com.br"
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard-tls #should match secret instead of certname for some reason
