apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-exp-pv
spec:
  capacity:
    storage: 500Gi # Adjust to your desired size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # NFS allows multiple pods to access data
  persistentVolumeReclaimPolicy: Retain # Keeps data if PVC is deleted
  nfs:
    path: /mnt/drivepool/kubernetes/immich
    server: 192.168.0.15
