argocd-apps:
  applications:
    argocd:
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/argo-cd
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd 
    argocd-apps:
      project: default
      syncPolicy:
        automated:
          enabled: true
          prune: false
          selfHeal: false
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/argocd-apps
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    observability:
      project: default
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/observability
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
    bw-secrets:
      project: default
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/secrets
      destination:
        server: https://kubernetes.default.svc
        namespace: secrets
    sealed-secrets:
      namespace: argocd
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/sealed-secrets 
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system

    immich:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/immich
      destination:
        server: https://kubernetes.default.svc
        namespace: immich
    # Example for a second app using the same repo:
    cert-manager:
      project: default
      namespace: argocd
      syncPolicy:
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/cert-manager
      destination:
        server: https://kubernetes.default.svc
        namespace: cert-manager
    pihole:
      enabled: false
      project: default
      namespace: argocd
      syncPolicy:
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/dns/pihole
      destination:
        server: https://kubernetes.default.svc
        namespace: pihole
    kube-vip:
      project: default
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
      source:
      - repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/kube-vip
      - repoURL: https://github.com/kube-vip/kube-vip-cloud-provider
        path: manifest
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
  #setup for gateway api + istio
    # istio:
    #   project: default
    #   syncPolicy:
    #     automated:
    #       enabled: true
    #       prune: true
    #       selfHeal: true
    #   source:
    #     repoURL: https://github.com/eduardoschulz/homelab.git 
    #     targetRevision: master
    #     path: charts/istio
    #   destination:
    #     server: https://kubernetes.default.svc
    #     namespace: kube-system
    # gateway-api-crds:
    #   project: default
    #   syncPolicy:
    #     automated:
    #       enabled: true
    #       prune: false #dont set to true
    #       selfHeal: true
    #   source:
    #   - repoURL: https://github.com/kubernetes-sigs/gateway-api
    #     path: config/crd/standard
    #     targetRevision: v1.2.0
    #   destination:
    #     server: https://kubernetes.default.svc
    #     namespace: default
