argocd-apps:
  applications:
    argocd:
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/argo-cd
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd 
    argocd-apps:
      project: default
      syncPolicy:
        automated:
          enabled: true
          prune: false
          selfHeal: false
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/argocd-apps
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    observability:
      project: default
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/observability
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
    sealed-secrets:
      namespace: argocd
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/sealed-secrets 
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system

    immich:
      namespace: immich
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/immich
      destination:
        server: https://kubernetes.default.svc
        namespace: immich
    # Example for a second app using the same repo:
    cert-manager:
      project: default
      namespace: argocd
      syncPolicy:
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/cert-manager
      destination:
        server: https://kubernetes.default.svc
        namespace: cert-manager
    pihole:
      enabled: false
      project: default
      namespace: argocd
      syncPolicy:
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
      source:
        repoURL: https://github.com/eduardoschulz/homelab.git 
        targetRevision: master
        path: charts/dns/pihole
      destination:
        server: https://kubernetes.default.svc
        namespace: pihole
