immich: 
  immich: 
    persistence:
      library:
        existingClaim: "immich-exp-nfs-pvc"

  server:
    enabled: true
    ingress:
      main:
        enabled: true 
        annotations:
          cert-manager.io/cluster-issuer: cloudflare-issuer
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: immich.eduardoschulz.com.br
            paths:
              - path: "/"
                service:
                  identifier: main
        tls:
          - secretName: immich-tls-cert
            hosts:
              - immich.eduardoschulz.com.br

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              pullPolicy: IfNotPresent
  machine-learning:
    enabled: false
    ingress:
      main:
        enabled: false
