cert-manager:
  crds:
    keep: true
    enabled: true
cloudflare:
  encryptedApiTokenKey: AgCIOxyyTbfalrAtjN12aJ+ooePXzpyijSQLfUQWn5clLXJfL0scnABLUD3/kkgI96N7dW1Wz+/MaWrKjnXmfLRw1XAstDDYy3D8X6tN2Akku4j7ojluhiuGU5bgBvMjJtPfyzGUPdBeufmyQPZInOPFLhFUm8cRtaRQNkuTZo7xz+5yH+23TtArgDYs/HRNzMRQdfFfRJCCkgL8/Jm4vCWZpAqounkiahWuJdPZ6XAe9KbhDrSQJO8yKGZ9B3dJrCbSnSJ4J9dNInL5JWWnfeZIjbO0c2MopaExAbKXZBAxY0ZbCk6yIDvOOuct+/eu3Y+4GUO9s7jw9Z5eX+BpLmfBjqg/lLZAedcT9qVoLmqU0pExuWhEuVsmT+YSCCS1KGeSyYQj9fHpBuhHMzbgy0+7pO7PotReXDxzNJ82ZzwjKQWOYVd30sLdMWrsuf7nDemhqmOp8U+kroaMFYfLB48LhPHq/zN0FL6jW9ZJQBPj4+gdeJRjt+k4U6FGFN0i4zy2lgNMvyzkJfPRTg4QBRZu1l+ISKIkmjeBwNFL/hzkrtG336Vyka3e7aZsTJ+5ZKY/qKNpC91Tohim9IqsYjPwf1laY1D24qfVEbRHoD2SKZt+6OD9B4sWoT4C+fBnkKxTacyWjFle5Vdf6G5yIt/E69CbmV6fDrJG81g+tfUqe4qef3Qq2E6O5I6AzGkuU9u2szAfeknxKzCGwT9ddB9CNahn8dvl+5T0TDZFYtS4c9uZ/pMYG25V 
letsencrypt:
  server: https://acme-v02.api.letsencrypt.org/directory
  email:
  privateKeySecretName:
